go_places/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('places/', views.places_index, name='index'),
  path('places/<int:place_id>/', views.places_detail, name='detail'),
  path('places/create/', views.PlaceCreate.as_view(), name='places_create'),
  path('places/<int:pk>/update/', views.PlaceUpdate.as_view(), name='places_update'),
  path('places/<int:pk>/delete/', views.PlaceDelete.as_view(), name='places_delete'),
  path('places/<int:place_id>/add_visit/', views.add_visit, name='add_visit'),
  path('places/<int:place_id>/add_todo/', views.add_todo, name='add_todo'),
  path('places/<int:place_id>/add_photo/', views.add_photo, name='add_photo'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

VISITED = (
  ('1', 'Visited'),
  ('2', 'Not Visited'),
  ('3', 'Planing To Visit')
)

class Place(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'place_id': self.id})

class Visit(models.Model):
  date = models.DateField('visiting date')
  visited = models.CharField(
    max_length=1,
    choices=VISITED,
    default=VISITED[0][0]
  )

  place = models.ForeignKey(Place, on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.get_visited_display()} on {self.date}"  

  class Meta:
    ordering = ['-date'] 

class Doing(models.Model):
  todo = models.CharField(max_length=100)
  complete = models.BooleanField(default=False)

  place = models.ForeignKey(Place, on_delete=models.CASCADE)
  def __str__(self):
    return self.todo  

class Photo(models.Model):
  url = models.CharField(max_length=200)
  place = models.ForeignKey(Place, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for place_id: {self.place_id} @{self.url}"     

main_app/forms.py
from django.forms import ModelForm
from .models import Visit, Doing


class VisitForm(ModelForm):
  class Meta:
    model = Visit
    fields = ['date', 'visited']

class DoingForm(ModelForm):
  class Meta:
    model = Doing
    fields = ['todo', 'complete']    

main_app/views.py
from unicodedata import name
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Place, Photo
from .forms import VisitForm, DoingForm
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
import uuid
import boto3


 # Create your views here.
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'go-places-calin'

def home(request):
    return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def places_index(request):
  places = Place.objects.filter(user=request.user)
  # cats = request.user.cat_set.all()
  return render(request, 'places/index.html', { 'places': places }) 

@login_required
def places_detail(request, place_id):
  place = Place.objects.get(id=place_id)
  visiting_form = VisitForm()
  todo_form = DoingForm()
  return render(request, 'places/detail.html', {
    'place': place, 
    'visiting_form': visiting_form, 
    'todo_form': todo_form
  })

@login_required
def add_visit(request, place_id):
  form = VisitForm(request.POST)
  if form.is_valid():
    new_visit = form.save(commit=False)
    new_visit.place_id = place_id
    new_visit.save()
  return redirect('detail', place_id=place_id)

@login_required
def add_todo(request, place_id):
  form = DoingForm(request.POST)
  if form.is_valid():
    new_todo = form.save(commit=False)
    new_todo.place_id = place_id
    new_todo.save()
  return redirect('detail', place_id=place_id)

@login_required
def add_photo(request, place_id):
    # photo-file will be the "name" attribute on the <input 
    # attemp to collect the photo file data
    photo_file = request.FILES.get('photo-file', None)
    # use conditional logic to determine if file is present
    if photo_file:
        # if it's present, we will create a referance to the boto3 client
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        # create a unique id for each photo file
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        # upload the photo file to aws s3
        try:
            # if succesfull
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            # 1) create photo instance with photo model and provide cat_id as foreign key val
            photo = Photo(url=url, place_id=place_id)
             # 2) save the photo instance to the database
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', place_id=place_id)         

class PlaceCreate(LoginRequiredMixin, CreateView):
  model = Place
  fields = ['name', 'description'] 
  success_url = '/places/'
  def form_valid(self, form):
    form.instance.user = self.request.user 
    return super().form_valid(form)

class PlaceUpdate(LoginRequiredMixin, UpdateView):
  model = Place
  fields = ['name', 'description'] 

class PlaceDelete(LoginRequiredMixin, DeleteView):
  model = Place 
  success_url = '/places/' 

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)  

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
    
<h1>About the Go Places App</h1>

<hr />

<h2>Why travelling?</h2>

<hr>

<p> Whatch the video and you'll find why :)</p>

<div class="embed-responsive embed-responsive-4by3" >
  <iframe width="700" height="400" src="https://www.youtube.com/embed/MyqhDKNig88" title="Why Traveling Is Important" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Go Places</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- link to  static -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>

  <body>
    <header>
      <!-- <style>
        .container{
         background-image: url("https://img.freepik.com/premium-vector/seamless-pattern-with-mountains-lettering-travel-vector-illustration_12196-339.jpg?w=2000")
         }
        .navbar{
           background:transparent !important;
         }
      </style> -->
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">Go Places</a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'about' %}"
                    >About</a
                  >
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Activities
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{% url 'places_create' %}"
                        >Add Activities</a
                      >
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'index' %}"
                        >View all my activities</a
                      >
                    </li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </li>
                  </ul>
                </li>

                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Places
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{% url 'places_create' %}"
                        >Add Places to go</a
                      >
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'index' %}"
                        >View all my places</a
                      >
                    </li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                      <a class="dropdown-item" href="#">Future enhancements</a>
                    </li>
                  </ul>
                </li>

                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'logout' %}"
                    >Log Out</a
                  >
                </li>

                {% else %}
                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'signup' %}"
                    >Sign Up</a
                  >
                </li>

                <li class="nav-item">
                  <a
                    class="nav-link active"
                    aria-current="page"
                    href="{% url 'login' %}"
                    >Log in</a
                  >
                </li>
                {% endif %}
              </ul>

              <form class="d-flex" role="search">
                <input
                  class="form-control me-2"
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                />
                <button class="btn btn-outline-success" type="submit">
                  Search
                </button>
                
              </form>
            </div>
          </div>
        </nav>
      </div>
    </header>

    <main class="container">{% block content %} {% endblock %}</main>
<!-- credit to mdbbootstrap.com for using their footer -->
    <div class="container my-5">
      <footer class="text-center text-white" style="background-color: #caced1">
        <!-- Grid container -->
        <div class="container p-4">
          <!-- Section: Images -->
          <section class="">
            <div class="row">
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/113.jpg"
                    class="w-100"
                  />
                  <a href="https://www.louvre.fr/en">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/111.jpg"
                    class="w-100"
                  />
                  <a href="#!">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/112.jpg"
                    class="w-100"
                  />
                  <a href="#!">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/114.jpg"
                    class="w-100"
                  />
                  <a href="#!">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/115.jpg"
                    class="w-100"
                  />
                  <a href="#!">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
              <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                <div
                  class="bg-image hover-overlay ripple shadow-1-strong rounded"
                  data-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/new/fluid/city/116.jpg"
                    class="w-100"
                  />
                  <a href="#!">
                    <div
                      class="mask"
                      style="background-color: rgba(251, 251, 251, 0.2)"
                    ></div>
                  </a>
                </div>
              </div>
            </div>
          </section>
          <!-- Section: Images -->
        </div>
        <!-- Grid container -->
        <div class="col-md-4 footer-nav animated fadeInUp">
            <div div class="col-md-6">
              <ul class="list">
                <li><a href="#">Contacts</a></li>
                <li><a href="#">Terms & Condition</a></li>
                <li><a href="#">Privacy Policy</a></li>
              </ul>
            </div>
        </div>
          <div class="col-md-2 footer-social animated fadeInDown">
            <h4>Follow Us</h4>
            <ul>
                <li><a href="https://github.com/Calinpet/Go_Places">Github</a></li>
                <li><a href="https://www.linkedin.com/in/calin-petrut/">LinkedIn</a></li>
               <li><a href="#">Instagram</a></li>
                <li><a href="#">Facebook</a></li>
             </ul>
          </div>
        
        <div
          class="text-center p-3"
          style="background-color: rgba(0, 0, 0, 0.2)"
        >
          © 2020 Copyright:
          <a class="text-white" href="https://mdbootstrap.com/"
            >All Rights Reserved, © 2022 Go Places Inc.</a
          >
        </div>
      </footer>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1> Go Places Home Page</h1>
<hr>
<h2>Welcome to Go Places! An application for enthusiastic 
  travelers!</h2>
 <p>What are you waiting for? Go buy a plane ticket!!</p> 
<hr>

<div id="carousel" class="carousel slide"data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="../static/images/california.jpeg" class="d-block w-100" alt="California">
    </div>
    <div class="carousel-item">
      <img src="../static/images/oradea.JPG" class="d-block w-100" alt="My Hometown">
    </div>
    <div class="carousel-item">
      <img src="../static/images/go_places.jpeg" class="d-block w-100" alt="Traveling the world">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


{% endblock %}

main_app/templates/main_app/place_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Place?</h1>
  <img src="{% static 'images/sad.png' %}" alt="A sad face"/>
</div>
<h2>Are you sure you want to delete {{ place.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'detail' place.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/place_form.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
  {% if object %}
  <h1>Edit {{place.name}}</h1>
  {% else %}
  <h1>Add a Place</h1>
  {% endif %}
</div>
{% comment %} 

{% endcomment %}
<form action="" method="post" class="form-container">
  {% comment %} 

  {% endcomment %}
  {% csrf_token %}
  <table>
    {% comment %}

    {% endcomment %}
    {{ form.as_table }}
  </table>
  <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock %}

main_app/templates/places/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Place Details</h1>
<!-- <div class="row"> -->
  <div class="card col-md-7 gx-5 mb-4 card text-bg-info mb-3">
    <div class="card text-bg-info mb-3">
      <div class="card-header"> {{ place.name }}</div>
      <p>Description: {{ place.description }}</p>
    </div>
      <div class="button-actions">
        <a href="{% url 'places_update' place.id %}" class="btn btn-warning btn-sm">Edit</a>
        <a href="{% url 'places_delete' place.id %}" class="btn btn-danger btn-sm">Delete</a>
    </div>
  </div>
  {% for photo in place.photo_set.all %}
  <img class="img-fluid card-panel" src="{{ photo.url }}" alt="Responsive image"/>
  <hr>
  {% empty %}
  <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}

  <form
    action="{% url 'add_photo' place.id %}"
    enctype="multipart/form-data"
    method="POST"
    class="card-panel"
    >
    {% csrf_token %}
    <input type="file" name="photo-file" />
    <br /><br />
    <input type="submit" class="btn btn-primary" value="Upload Photo" />
  </form>
  
</div>

<hr>

<div class="row">
  <div class="todos-container">
    <section class="todos">
      <div class="subsection-title">
        <h1>Things to do in {{ place.name }}!!</h1>
      </div>
      <table>
        <thead>
          <tr><th>
            <form
            action="{% url 'add_todo' place.id %}" 
            method="post" 
            class="subsection-content"
          >
            {% csrf_token %}
            {{ todo_form.as_p }}
            <br>
            <button type="submit" class="btn btn-primary">Add</button>
          </form>

            </form>
          </th></tr>
        </thead>
        <tbody>
          {% for doing in place.doing_set.all %}
            <tr>
              {% if doing.complete %}
                <td>✔️{{doing.todo}}</td>
                {% comment %} <td>✔️{{doing.get_todo_display}}</td> {% endcomment %}
              {% else %}
                <td>{{doing.todo}}</td>
                {% comment %} <td>{{doing.get_todo_display}}</td> {% endcomment %}
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </section>   
  </div>
</div>

<hr>

<div class="visits-container">
  <section class="visits">
    <div class="subsection-title">
      <h2>Visits</h2>
      <!-- probably image -->
    </div>
    <h3>Add a Visit</h3>
    <form
      action="{% url 'add_visit' place.id %}" 
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ visiting_form.as_p }}
      <button type="submit" class="btn btn-primary" >Add</button>
    </form>

    <h3>Past Visits</h3>

    {% if place.visit_set.all.count %}
    <table>
      <thead>
        <tr><th>Date</th><th>Visit</th></tr>
      </thead>
      <tbody>
        {% for visit in place.visit_set.all %}
          <tr>
            <td>{{visit.date}}</td>
            <td>{{visit.get_visited_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
			<div class="subsection-content">
        <p>Let's Goooo! Buy a plane ticket to {{place.name}}!!!</p>
      </div>
    {% endif %}
  </section>
</div>
<hr>

<script type="text/javascript">
  $(function() {
      $('#datepicker').datepicker();
  });
</script>


{% endblock %}

main_app/templates/places/index.html
{% extends 'base.html' %} {% block content %}

<h1>Places List</h1>

{% for place in places %}
<!-- <section class="card-container">
  <div class="container"> -->
    <div class="row g-3">
      <div class="col-8 col-md-8 col-lg-6">
        <!-- <hr> -->
        <div class="card card border-warning mb-3 card text-bg-warning mb-3" >
          <a href="{% url 'detail' place.id %}">
            <div class="card-content">
              <div class="card-img-container">
              <div class="card-header">{{ place.name }}</div>
              <p class="card-text">Description: {{ place.description }}</p>
            </div>
          </a>
        </div>
      </div>  
    </div>
  <!-- </div>     -->
  {% endfor %}
<!-- </section> -->
 
{% endblock %}